Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'PSIT.FrontendLogin:NeosBackend':
                pattern: PSIT\FrontendLogin\Security\NeosRequestPattern
          'PSIT.FrontendLogin:Frontend':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              'PSIT.FrontendLogin:NeosFrontend':
                pattern: PSIT\FrontendLogin\Security\NeosRequestPattern
                patternOptions:
                  matchFrontend: true
  Neos:
    userInterface:
      translation:
        autoInclude:
          PSIT.FrontendLogin:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        PSIT.FrontendLogin: true

PSIT:
  FrontendLogin:
    translation:
      packageKey: 'PSIT.FrontendLogin'
      sourceName: 'Main'
